#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Dracula'
ICONS='WhiteSur-dark'
FONT='Roboto Regular 12'
CURSOR='McMojave Cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
# loginctl session-status | awk -F ' ' 'NR==1{print $1}'