#!/bin/bash

# Colors
# bg='1e1e2e' bgl='313244' fg='d9e0ee'
# red='f38ba8' green='a6e3a1' yellow='f9e2af'
# blue='89b4fa' magenta='cba6f7' cyan='89dceb'
# alpha='00000000'

# # CMD
# swaylock -f \
# 	`# General` \
# 	--ignore-empty-password \
# 	--show-failed-attempts \
# 	--hide-keyboard-layout \
# 	--indicator-caps-lock \
# 	`# Appearance - change CC to your desired transparency` \
# 	--color ${bg}FF \
# 	`#--image ${IMAGE} --scaling fill` \
# 	--font 'Roboto Medium' --font-size 30 \
# 	`# Backspace Key` \
# 	--key-hl-color ${green} \
# 	--caps-lock-key-hl-color ${blue} \
# 	--bs-hl-color ${red} \
# 	--caps-lock-bs-hl-color ${red} \
# 	`# Indicator` \
# 	--indicator-radius 120 \
# 	--indicator-thickness 10 \
# 	`# Inside Circle Colors` \
# 	--inside-color ${alpha} \
# 	--inside-clear-color ${alpha} \
# 	--inside-caps-lock-color ${alpha} \
# 	--inside-ver-color ${blue} \
# 	--inside-wrong-color ${red} \
# 	`# Layout Colors` \
# 	--layout-bg-color ${cyan} \
# 	--layout-border-color ${cyan} \
# 	--layout-text-color ${bg} \
# 	`# Line Colors` \
# 	--line-color ${bg} \
# 	--line-clear-color ${red} \
# 	--line-caps-lock-color ${bg} \
# 	--line-ver-color ${bg} \
# 	--line-wrong-color ${bg} \
# 	`# Ring Colors` \
# 	--ring-color ${cyan} \
# 	--ring-clear-color ${bg} \
# 	--ring-caps-lock-color ${magenta} \
# 	--ring-ver-color ${blue} \
# 	--ring-wrong-color ${red} \
# 	`# Separator Color` \
# 	--separator-color ${bg} \
# 	`# Text Colors` \
# 	--text-color ${fg} \
# 	--text-clear-color ${fg} \
# 	--text-caps-lock-color ${fg} \
# 	--text-ver-color ${bg} \
# 	--text-wrong-color ${bg} \
# 	--indicator-caps-lock

swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	--ring-color bb00cc \
	--key-hl-color 880033 \
	--line-color 00000000 \
	--inside-color 00000088 \
	--separator-color 00000000 \
	--grace 2 \
	--fade-in 0.2 \
	--color=1e1e2e \
	--bs-hl-color=f5e0dc \
	--caps-lock-bs-hl-color=f5e0dc \
	--caps-lock-key-hl-color=a6e3a1 \
	--inside-color=00000000 \
	--inside-clear-color=00000000 \
	--inside-caps-lock-color=00000000 \
	--inside-ver-color=00000000 \
	--inside-wrong-color=00000000 \
	--key-hl-color=a6e3a1 \
	--layout-bg-color=00000000 \
	--layout-border-color=00000000 \
	--layout-text-color=cdd6f4 \
	--line-color=00000000 \
	--line-clear-color=00000000 \
	--line-caps-lock-color=00000000 \
	--line-ver-color=00000000 \
	--line-wrong-color=00000000 \
	--ring-color=b4befe \
	--ring-clear-color=f5e0dc \
	--ring-caps-lock-color=fab387 \
	--ring-ver-color=89b4fa \
	--ring-wrong-color=eba0ac \
	--separator-color=00000000 \
	--text-color=cdd6f4 \
	--text-clear-color=f5e0dc \
	--text-caps-lock-color=fab387 \
	--text-ver-color=89b4fa \
	--text-wrong-color=eba0ac \